### ISSUE TITLE
Revisit the welcome screen

### ISSUE THREAD

**Issue by jgonggrijp** [UUDigitalHumanitieslab/readit-interface#105]
Follow-up on #3 and #7.

- [ ] Simple google-like search field that leads to the search results screen (#31).
- [ ] 3 (ish) randomly selected "featured" items or sources, leading directly to the explorer (#63).
- [ ] A "discover more" button (or similar text), leading to the discover by category screen (#104).
