### ISSUE TITLE
Search and exploration aspect

### ISSUE THREAD

**Issue by jgonggrijp** [UUDigitalHumanitieslab/readit-interface#106]
Aspect module that connects event bindings between the following global instances:

- [ ] A `Graph` (#11) with our core vocabulary (#83).
- [ ] A `Graph` with the project ontology (#82).
- [ ] Welcome page view (#105).
- [ ] Explore by category view (#104).
- [ ] Search results view (#31).
- [x] Right-scrolling explorer view (#63).
- [x] Exploration router (#62).
- [ ] Perhaps a query model to represent the (potentially complex) search issued by the user (new issue to be created).

The events to bind simply follow from intuition about what the application should do. For example, if you click on a featured item on the welcome page, the item in question should be displayed in the explorer and the route should reflect this change of context.
